grafana:
  adminPassword: admin
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.localhost
    path: /
  nodeSelector:
    devplane.io/node-group: observability
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.observability.svc.cluster.local
          isDefault: false
        - name: Tempo
          type: tempo
          access: proxy
          url: http://tempo.observability.svc.cluster.local:3100
          isDefault: false
        - name: Mimir
          type: prometheus
          access: proxy
          url: http://mimir-nginx.observability.svc.cluster.local/prometheus
          isDefault: true
