vector:
  role: Stateless-Aggregator
  replicas: 1
  nodeSelector:
    devplane.io/node-pool: addons
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      memory: 256Mi
  service:
    enabled: true
    ports:
      - name: otlp-grpc
        port: 4317
        protocol: TCP
      - name: otlp-http
        port: 4318
        protocol: TCP
  customConfig:
    data_dir: /vector-data-dir
    sources:
      otlp:
        type: opentelemetry
        grpc:
          address: 0.0.0.0:4317
        http:
          address: 0.0.0.0:4318
    sinks:
      loki:
        type: loki
        inputs:
          - otlp.logs
        endpoint: http://loki-gateway.observability.svc.cluster.local
        labels:
          source: devplane
        encoding:
          codec: json
      mimir:
        type: prometheus_remote_write
        inputs:
          - otlp.metrics
        endpoint: http://mimir-nginx.observability.svc.cluster.local/api/v1/push
      tempo:
        type: opentelemetry
        inputs:
          - otlp.traces
        protocol:
          type: grpc
          uri: http://tempo.observability.svc.cluster.local:4317
