apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: agent-addons
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - chart: opentelemetry-collector
  template:
    metadata:
      name: 'agent-{{chart}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/gleydsoncavalcanti/devplane.git
        targetRevision: main
        path: charts/agents/{{chart}}
        helm:
          releaseName: '{{chart}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
