apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: observability-addons
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - chart: mimir
          - chart: loki
          - chart: tempo
          - chart: grafana
  template:
    metadata:
      name: 'observability-{{chart}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/gleydsoncavalcanti/devplane.git
        targetRevision: main
        path: charts/observability/{{chart}}
        helm:
          releaseName: '{{chart}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: observability
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
