argo-cd:
  global:
    domain: argo.devplane

  configs:
    params:
      server.insecure: true

  server:
    nodeSelector:
      devplane.io/node-pool: addons
    service:
      type: ClusterIP
    ingress:
      enabled: true
      controller: generic
      ingressClassName: nginx
      hostname: argo.devplane
      path: /
      pathType: Prefix
      tls: false
      extraTls: []

  controller:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons

  repoServer:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons

  applicationSet:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons

  notifications:
    enabled: false

  dex:
    enabled: false
