argo-cd:
  global:
    domain: argocd.localhost

  configs:
    params:
      server.insecure: true

  server:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      controller: generic
      ingressClassName: nginx
      hostname: argocd.localhost
      path: /
      pathType: Prefix
      tls: false
      extraTls: []

  controller:
    replicas: 1

  repoServer:
    replicas: 1

  applicationSet:
    replicas: 1

  notifications:
    enabled: false

  dex:
    enabled: false
