devplane-application:
  app:
    name: contabilidade
    domain: contabilidade.devplane
    replicaCount: 1

  image:
    repository: ghcr.io/gleydsoncavalcanti/devplane-sample-contabilidade
    tag: latest

  postgres:
    enabled: true
    database: contabilidade
    username: contabilidade
    password: contabilidade

  observability:
    enabled: true
    logs:
      enabled: true
    metrics:
      enabled: true
    traces:
      enabled: false
    datastore:
      logs: loki
      metrics: mimir
      traces: tempo
