apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: produtos
  namespace: argocd
  labels:
    devplane.io/app-template: produtos
spec:
  project: default
  source:
    repoURL: https://github.com/gleydsoncavalcanti/devplane.git
    targetRevision: main
    path: apps/produtos
    helm:
      releaseName: produtos
  destination:
    server: https://kubernetes.default.svc
    namespace: produtos
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
