kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devplane-runtime
nodes:
  - role: control-plane
  - role: worker
    labels:
      devplane.io/node-group: app
  - role: worker
    labels:
      devplane.io/node-group: observability
  - role: worker
    labels:
      devplane.io/node-group: databases
