tempo:
  nodeSelector:
    devplane.io/node-pool: addons
  tempo:
    storage:
      trace:
        backend: s3
        s3:
          bucket: tempo
          endpoint: mimir-minio.observability.svc.cluster.local:9000
          access_key: grafana-mimir
          secret_key: supersecret
          insecure: true
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
