apiVersion: v2
name: devplane-vault
description: DevPlane Vault wrapper chart.
type: application
version: 0.1.0
appVersion: "1.21.2"
dependencies:
  - name: vault
    version: "0.32.0"
    repository: https://helm.releases.hashicorp.com
