vault:
  global:
    enabled: true
    tlsDisable: true

  injector:
    enabled: true
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons

  server:
    nodeSelector:
      devplane.io/node-pool: addons
    dev:
      enabled: true
      devRootToken: root
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: vault.devplane
          paths:
            - /
      tls: []
    dataStorage:
      enabled: false
    auditStorage:
      enabled: false

  ui:
    enabled: true
    serviceType: ClusterIP
