vault:
  global:
    enabled: true
    tlsDisable: true

  injector:
    enabled: true
    replicas: 1

  server:
    dev:
      enabled: true
      devRootToken: root
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: vault.localhost
          paths:
            - /
      tls: []
    dataStorage:
      enabled: false
    auditStorage:
      enabled: false

  ui:
    enabled: true
    serviceType: ClusterIP
