mimir-distributed:
  minio:
    enabled: true
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
    buckets:
      - name: mimir-tsdb
        policy: none
        purge: false
      - name: mimir-ruler
        policy: none
        purge: false
      - name: tempo
        policy: none
        purge: false
  gateway:
    enabled: false
    enabledNonEnterprise: false
    nodeSelector:
      devplane.io/node-pool: addons
  nginx:
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
  distributor:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 384Mi
  ingester:
    replicas: 1
    zoneAwareReplication:
      enabled: false
    persistentVolume:
      enabled: false
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 512Mi
  querier:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 384Mi
  query_frontend:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 25m
        memory: 96Mi
      limits:
        memory: 256Mi
  query_scheduler:
    enabled: false
  compactor:
    persistentVolume:
      enabled: false
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 50m
        memory: 192Mi
      limits:
        memory: 512Mi
  overrides_exporter:
    enabled: false
  store_gateway:
    replicas: 1
    persistentVolume:
      enabled: false
    zoneAwareReplication:
      enabled: false
    nodeSelector:
      devplane.io/node-pool: addons
    resources:
      requests:
        cpu: 50m
        memory: 192Mi
      limits:
        memory: 512Mi
  ruler:
    enabled: false
  alertmanager:
    enabled: false
  rollout_operator:
    enabled: false
