mimir-distributed:
  minio:
    enabled: true
    nodeSelector:
      devplane.io/node-pool: addons
    buckets:
      - name: mimir-tsdb
        policy: none
        purge: false
      - name: mimir-ruler
        policy: none
        purge: false
      - name: tempo
        policy: none
        purge: false
  gateway:
    enabledNonEnterprise: true
    nodeSelector:
      devplane.io/node-pool: addons
  nginx:
    nodeSelector:
      devplane.io/node-pool: addons
  distributor:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons
  ingester:
    replicas: 1
    zoneAwareReplication:
      enabled: false
    persistentVolume:
      enabled: false
    nodeSelector:
      devplane.io/node-pool: addons
  querier:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons
  query_frontend:
    replicas: 1
    nodeSelector:
      devplane.io/node-pool: addons
  compactor:
    persistentVolume:
      enabled: false
    nodeSelector:
      devplane.io/node-pool: addons
  store_gateway:
    replicas: 1
    persistentVolume:
      enabled: false
    zoneAwareReplication:
      enabled: false
    nodeSelector:
      devplane.io/node-pool: addons
  ruler:
    enabled: false
  alertmanager:
    enabled: false
