apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devplane-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devplane-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "devplane-application.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "devplane-application.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
      annotations:
        devplane.io/observability-enabled: {{ .Values.observability.enabled | quote }}
        devplane.io/logs-enabled: {{ .Values.observability.logs.enabled | quote }}
        devplane.io/metrics-enabled: {{ .Values.observability.metrics.enabled | quote }}
        devplane.io/traces-enabled: {{ .Values.observability.traces.enabled | quote }}
        devplane.io/logs-datastore: {{ .Values.observability.datastore.logs | quote }}
        devplane.io/metrics-datastore: {{ .Values.observability.datastore.metrics | quote }}
        devplane.io/traces-datastore: {{ .Values.observability.datastore.traces | quote }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- if .Values.postgres.enabled }}
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "devplane-application.postgresName" . }}:5432/{{ .Values.postgres.database }}"
            {{- end }}
            - name: OTEL_SERVICE_NAME
              value: {{ .Values.app.name | quote }}
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://opentelemetry-collector.observability.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: DEVPLANE_OBSERVABILITY_LOGS
              value: {{ .Values.observability.logs.enabled | quote }}
            - name: DEVPLANE_OBSERVABILITY_METRICS
              value: {{ .Values.observability.metrics.enabled | quote }}
            - name: DEVPLANE_OBSERVABILITY_TRACES
              value: {{ .Values.observability.traces.enabled | quote }}
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
