{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "devplane-application.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devplane-application.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.app.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "devplane-application.fullname" . }}
                port:
                  name: http
{{- end }}
