{{- if .Values.postgres.enabled }}
{{- if .Values.postgres.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "devplane-application.postgresName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devplane-application.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
---
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devplane-application.postgresName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devplane-application.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "devplane-application.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "devplane-application.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "devplane-application.postgresName" . }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          {{- if .Values.postgres.storage.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "devplane-application.postgresName" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "devplane-application.postgresName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devplane-application.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    {{- include "devplane-application.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end }}
