apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devplane-portal.fullname" . }}
  namespace: portal
  labels:
    {{- include "devplane-portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "devplane-portal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "devplane-portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: portal
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: portal-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: portal-html
          configMap:
            name: {{ include "devplane-portal.fullname" . }}
